package com.proman.server.db.model.dao.proman.impl;

import com.proman.server.db.model.obj.proman.StudentGrades;
import org.springframework.stereotype.Repository;

import com.github.wwadge.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.proman.server.db.model.dao.proman.StudentGradesDao;
 
 
/**
 * DAO for table: StudentGrades.
 * @author autogenerated
 */
@Repository
public class StudentGradesDaoImpl extends GenericHibernateDaoImpl<StudentGrades, String> implements StudentGradesDao {
	
	/** Constructor method. */
		public StudentGradesDaoImpl() {
			super(StudentGrades.class);
		}
	}

