package com.proman.server.db.model.dao.proman.impl;

import com.proman.server.db.model.obj.proman.Student;
import org.springframework.stereotype.Repository;

import com.github.wwadge.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.proman.server.db.model.dao.proman.StudentDao;
 
 
/**
 * DAO for table: Student.
 * @author autogenerated
 */
@Repository
public class StudentDaoImpl extends GenericHibernateDaoImpl<Student, Integer> implements StudentDao {
	
	/** Constructor method. */
		public StudentDaoImpl() {
			super(Student.class);
		}
	}

