package com.proman.server.db.model.dao.proman.impl;

import com.proman.server.db.model.obj.proman.TeamStudentPK;
import org.springframework.stereotype.Repository;

import com.github.wwadge.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.proman.server.db.model.dao.proman.TeamStudentPKDao;
import java.io.Serializable;
 
/**
 * DAO for table: TeamStudentPK.
 * @author autogenerated
 */
@Repository
public class TeamStudentPKDaoImpl extends GenericHibernateDaoImpl<TeamStudentPK, Serializable> implements TeamStudentPKDao {
	
	/** Constructor method. */
		public TeamStudentPKDaoImpl() {
			super(TeamStudentPK.class);
		}
	}

