package com.proman.server.db.model.dao.proman.impl;

import com.proman.server.db.model.obj.proman.TeamManager;
import org.springframework.stereotype.Repository;

import com.github.wwadge.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.proman.server.db.model.dao.proman.TeamManagerDao;
 
 
/**
 * DAO for table: TeamManager.
 * @author autogenerated
 */
@Repository
public class TeamManagerDaoImpl extends GenericHibernateDaoImpl<TeamManager, Integer> implements TeamManagerDao {
	
	/** Constructor method. */
		public TeamManagerDaoImpl() {
			super(TeamManager.class);
		}
	}

