package com.proman.server.db.model.dao.proman.impl;

import com.proman.server.db.model.obj.proman.UserDetails;
import org.springframework.stereotype.Repository;

import com.github.wwadge.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.proman.server.db.model.dao.proman.UserDetailsDao;
 
 
/**
 * DAO for table: UserDetails.
 * @author autogenerated
 */
@Repository
public class UserDetailsDaoImpl extends GenericHibernateDaoImpl<UserDetails, Integer> implements UserDetailsDao {
	
	/** Constructor method. */
		public UserDetailsDaoImpl() {
			super(UserDetails.class);
		}
	}

