package com.proman.server.db.model.dao.proman.impl;

import com.proman.server.db.model.obj.proman.UserRoles;
import org.springframework.stereotype.Repository;

import com.github.wwadge.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.proman.server.db.model.dao.proman.UserRolesDao;
 
 
/**
 * DAO for table: UserRoles.
 * @author autogenerated
 */
@Repository
public class UserRolesDaoImpl extends GenericHibernateDaoImpl<UserRoles, String> implements UserRolesDao {
	
	/** Constructor method. */
		public UserRolesDaoImpl() {
			super(UserRoles.class);
		}
	}

