package com.proman.server.db.model.dao.proman;

import com.github.wwadge.hbnpojogen.persistence.GenericDAO;
import com.proman.server.db.model.obj.proman.Institution;
 
/**
 * DAO interface for table: Institution.
 * @author autogenerated
 */
public interface InstitutionDao extends GenericDAO<Institution,  Integer>  {
	// constructor only
}

