package com.proman.server.db.model.dao.proman;

import com.github.wwadge.hbnpojogen.persistence.GenericDAO;
import com.proman.server.db.model.obj.proman.SchemaVersion;
 
/**
 * DAO interface for table: SchemaVersion.
 * @author autogenerated
 */
public interface SchemaVersionDao extends GenericDAO<SchemaVersion,  Integer>  {
	// constructor only
}

