package com.proman.server.db.model.dao.proman;

import com.proman.server.db.model.obj.proman.StudentGrades;
import com.github.wwadge.hbnpojogen.persistence.GenericDAO;
 
/**
 * DAO interface for table: StudentGrades.
 * @author autogenerated
 */
public interface StudentGradesDao extends GenericDAO<StudentGrades,  String>  {
	// constructor only
}

