package com.proman.server.db.model.dao.proman;

import com.github.wwadge.hbnpojogen.persistence.GenericDAO;
import com.proman.server.db.model.obj.proman.Student;
 
/**
 * DAO interface for table: Student.
 * @author autogenerated
 */
public interface StudentDao extends GenericDAO<Student,  Integer>  {
	// constructor only
}

