package com.proman.server.db.model.dao.proman;

import com.github.wwadge.hbnpojogen.persistence.GenericDAO;
import com.proman.server.db.model.obj.proman.TeamManager;
 
/**
 * DAO interface for table: TeamManager.
 * @author autogenerated
 */
public interface TeamManagerDao extends GenericDAO<TeamManager,  Integer>  {
	// constructor only
}

