package com.proman.server.db.model.dao.proman;

import com.github.wwadge.hbnpojogen.persistence.GenericDAO;
import com.proman.server.db.model.obj.proman.Team;
 
/**
 * DAO interface for table: Team.
 * @author autogenerated
 */
public interface TeamDao extends GenericDAO<Team,  Integer>  {
	// constructor only
}

