package com.proman.server.db.model.dao.proman;

import com.proman.server.db.model.obj.proman.TeamStudentPK;
import java.io.Serializable;

import com.github.wwadge.hbnpojogen.persistence.GenericDAO;
/**
 * DAO interface for table: TeamStudentPK.
 * @author autogenerated
 */
public interface TeamStudentPKDao extends GenericDAO<TeamStudentPK,  Serializable>  {
	// constructor only
}

