package com.proman.server.db.model.dao.proman;

import com.github.wwadge.hbnpojogen.persistence.GenericDAO;
import com.proman.server.db.model.obj.proman.TeamManagerMapPK;
import java.io.Serializable;
/**
 * DAO interface for table: TeamManagerMapPK.
 * @author autogenerated
 */
public interface TeamManagerMapPKDao extends GenericDAO<TeamManagerMapPK,  Serializable>  {
	// constructor only
}

