package com.proman.server.db.model.dao.proman;

import com.github.wwadge.hbnpojogen.persistence.GenericDAO;
import com.proman.server.db.model.obj.proman.TeamManagerMap;
import com.proman.server.db.model.obj.proman.TeamManagerMapPK;
/**
 * DAO interface for table: TeamManagerMap.
 * @author autogenerated
 */
public interface TeamManagerMapDao extends GenericDAO<TeamManagerMap,  TeamManagerMapPK>  {
	// constructor only
}

