package com.proman.server.db.model.dao.proman;

import com.github.wwadge.hbnpojogen.persistence.GenericDAO;
import com.proman.server.db.model.obj.proman.TeamStudent;
import com.proman.server.db.model.obj.proman.TeamStudentPK;
/**
 * DAO interface for table: TeamStudent.
 * @author autogenerated
 */
public interface TeamStudentDao extends GenericDAO<TeamStudent,  TeamStudentPK>  {
	// constructor only
}

