package com.proman.server.db.model.dao.proman;

import com.github.wwadge.hbnpojogen.persistence.GenericDAO;
import com.proman.server.db.model.obj.proman.UserDetails;
 
/**
 * DAO interface for table: UserDetails.
 * @author autogenerated
 */
public interface UserDetailsDao extends GenericDAO<UserDetails,  Integer>  {
	// constructor only
}

