package com.proman.server.db.model.dao.proman;

import com.github.wwadge.hbnpojogen.persistence.GenericDAO;
import com.proman.server.db.model.obj.proman.UserRoles;
 
/**
 * DAO interface for table: UserRoles.
 * @author autogenerated
 */
public interface UserRolesDao extends GenericDAO<UserRoles,  String>  {
	// constructor only
}

