package com.proman.server.db.model.dao.proman;

import com.github.wwadge.hbnpojogen.persistence.GenericDAO;
import com.proman.server.db.model.obj.proman.Users;
 
/**
 * DAO interface for table: Users.
 * @author autogenerated
 */
public interface UsersDao extends GenericDAO<Users,  Integer>  {
	// constructor only
}

